export const PULL_QUOTE = "PULL_QUOTE";

export const UPDATE_SOURCE = "UPDATE_SOURCE";
export const TEST_NEW_SOURCE = "TEST_NEW_SOURCE";

export const CHANGE_SOURCE_SUBSCRIPTION = "CHANGE_SOURCE_SUBSCRIPTION";
