
export const PULL_USER_DATA__PULLED = "PULL_USER_DATA__PULLED";
export const PULL_USER_DATA__PULLING = "PULL_USER_DATA__PULLING";
export const PULL_USER_DATA__FAILED = "PULL_USER_DATA__FAILED";

export const PULL_USER_SETTINGS_DATA__PULLED = "PULL_USER_SETTINGS_DATA__PULLED";
export const PULL_USER_SETTINGS_DATA__PULLING = "PULL_USER_SETTINGS_DATA__PULLING";
export const PULL_USER_SETTINGS_DATA__FAILED = "PULL_USER_SETTINGS_DATA__FAILED";

export const PUSH_QUOTE_DATA__PUSHED = "PUSH_QUOTE_DATA__PUSHED";
export const PUSH_QUOTE_DATA__PUSHING = "PUSH_QUOTE_DATA__PUSHING";
export const PUSH_QUOTE_DATA__FAILED = "PUSH_QUOTE_DATA__FAILED";

export const CHANGE_LOCAL_QUOTE_DATA = "CHANGE_LOCAL_QUOTE_DATA";

export const PULL_QUOTE_DATA__PULLED = "PULL_QUOTE_DATA__PULLED";
export const PULL_QUOTE_DATA__PULLING = "PULL_QUOTE_DATA__PULLING";
export const PULL_QUOTE_DATA__FAILED = "PULL_QUOTE_DATA__FAILED";

export const UPVOTE_QUOTE__PUSHED = "UPVOTE_QUOTE__PUSHED";
export const UPVOTE_QUOTE__PUSHING = "UPVOTE_QUOTE__PUSHING";
export const UPVOTE_QUOTE__FAILED = "UPVOTE_QUOTE__FAILED";

export const DOWNVOTE_QUOTE__PUSHED = "DOWNVOTE_QUOTE__PUSHED";
export const DOWNVOTE_QUOTE__PUSHING = "DOWNVOTE_QUOTE__PUSHING";
export const DOWNVOTE_QUOTE__FAILED = "DOWNVOTE_QUOTE__FAILED";
